### ISSUE TITLE
What is sequence:position? 

### ISSUE THREAD

**Issue by Yehouda** [diasbruno/cl-bnf#14]
In the file src/bnf.lisp it uses **sequence:position** several times. 

Where is the package "SEQUENCE" supposed to come from? 

Isn't it just the standard function **position**?

**Comment by diasbruno** [comment]
It's possible, maybe I've just looked something on the internet and added it.
I'll check it.

**Comment by diasbruno** [comment]
Now it uses the standard `position`. Thanks.

**Comment by diasbruno** [comment]
I think it uses `sb-sequence:position`.
