### ISSUE TITLE
define-grammar defines the stuff only at compile file

### ISSUE THREAD

**Issue by Yehouda** [diasbruno/cl-bnf#15]
**define-grammar ** in src/bnf.lisp defines the rules only at compile time, so it doesn't work if you load the compiled file without actually compiling. 

For example, **(ql:quickload "cl-bnf-examples"**) so it compile and load everything. Quit the image you are running and start it again. Then  **(ql:quickload "cl-bnf-examples")**  again. This loads the compiled files, and errors because none of the rules in the **json** grammar are defined.

**Comment by diasbruno** [comment]
This is something I don't have much experience with (working with `eval-when`). 
Do I miss to include `:load-toplevel`? 
I'll make some tests.

**Comment by Yehouda** [comment]
Adding :load-toplevel fixes it. 

But it is not obvious to me that you need eval-when at all. Looks to me that you can just use progn instead, because it does not define anything that would normally be needed during compilation. 

If the user wants to use what define-grammar defines during compilation, they can wrap it with eval-when themselves.

**Comment by diasbruno** [comment]
It seems right. I'll fix it.

**Comment by diasbruno** [comment]
Sorry for the delay. It should be fixed now.

**Comment by diasbruno** [comment]
Thanks!
