### ISSUE TITLE
Macro in the keyword package

### ISSUE THREAD

**Issue by Harleqin** [diasbruno/cl-bnf#6]
The macro `:=` is named by the symbol named `=` in the keyword package.  The exported symbol `cl-bnf:|:=|` has nothing to do with it.

As soon as the system is loaded, the macro is available from the keyword package:

    CL-USER> (ql:quickload "cl-bnf")
    To load "cl-bnf":
      Load 1 ASDF system:
        asdf
      Install 1 Quicklisp release:
        cl-bnf
    ; Fetching #<URL "http://beta.quicklisp.org/archive/cl-bnf/2018-07-11/cl-bnf-20180711-git.tgz">
    ; 4.94KB
    ==================================================
    5,054 bytes in 0.00 seconds (0.00KB/sec)
    ; Loading "cl-bnf"
    [package cl-bnf].
    ("cl-bnf")
    CL-USER> (:= foo (:char #\a))
    FOO

    CL-USER> (describe 'cl-bnf:|:=|)
    CL-BNF:|:=|
      [symbol]
    ; No value
    CL-USER> (describe :=)
    :=
      [symbol]
    
    = names a constant variable:
      Value: :=
    
    = names a macro:
      Lambda-list: (LABEL RULE &KEY CALL TAG APPLY)
      Documentation:
        Generate a function LABEL to parse RULE. Later,
        you can apply a TRANSFORMATION which can be a function
        or a keytword.
      Source file: /home/svante/quicklisp/dists/quicklisp/software/cl-bnf-20180711-git/bnf.lisp
    ; No value
    CL-USER>

I do not think that this was intended, and I feel that it is less than ideal that the (global) keyword package gets filled with library code.

**Comment by diasbruno** [comment]
@Harleqin Thanks for bring this up. I'm still thinking on a better (proper) way to write the rules. I'll do some work on the weekend to improve this. Any suggestions?

**Comment by Harleqin** [comment]
The obvious solution that changes as little as possible is to actually name the macro `cl-bnf:|:=|`.  You'd need to write `(defmacro |:=| …)` or `(defmacro \:= …)`, and every invocation would need to be changed as well.

Going a bit further would be to rename it to `defrule` or `define-rule`.  This would also make it clearer that it is a toplevel definition (I had to look twice at the documentation to understand this).

Thinking a bit more about it, as a user I'd maybe not want the rules to be global, but always part of a grammar, so that I can define several grammars in one program without name clashes.  You can then maybe keep the `:=`, because it would be interpreted by a `defgrammar` macro, instead of being a macro itself.

    (defgrammar json-number ()
      (:= decimal-number (:many (:one #'numeric-char-p)))
      (:= real-number (:or (:and #'decimal-number
                                 (:char #\.)
                                 #'decimal-number)
                           (:and #'decimal-number
                                 (:char #\.))))
      (:= signed-part (:or (:char #\+) (:char #\-)))
      (:= exp-chars (:or (:char #\e)
                         (:char #\E)))
      (:= exp-part (:or (:and #'exp-chars
                              #'signed-part
                              #'decimal-number)
                        (:and #'exp-chars
                              #'decimal-number)))
      (:= numeric (:or #'real-number
                       #'decimal-number))
      (:= number-literal (:or (:and #'numeric
                                    #'exp-part)
                              #'numeric)
          :call (lambda (matches)
                  (cons :number (stringify matches))))
    
    (parse json-number number-literal "1e3")

**Comment by Harleqin** [comment]
Yes, but also extending grammars, or importing rules from other grammars might be possible.  It is quite similar to packages and symbols, but I'd tend not to try to map the former to the latter, because they operate on different semantic levels.
